### ISSUE TITLE
Lesson 5 - Predicting plant growth with IoT

### ISSUE THREAD

**Issue by jimbobbennett** [microsoft/IoT-For-Beginners#12]
# Lesson

## Concepts taught

* IoT can be used to improve agriculture to help feed the growing global population.
* Sensor data can help with prediction of plant growth and maturity.

## Learning objectives

* Learn about digital agriculture and ways IoT is helping increase growth yields.
* Learn about measuring temperatures and calculating growing-degree days.

## Hardware required

* Wio/Pi
* Grove temperature sensor

## Software/services

* VS Code
* PlatformIO (Wio)

## Code

* On-device code to capture temperature sensor readings.
* Calculation on-device of growing-degree day measurements for a given base temperature
* Jupyter notebook to visualize growing degree day data

# Tasks

- [x] Write lesson
- [x] Build and test lab - Wio Terminal
- [x] Build and test lab - Raspberry Pi
- [x] Build and test lab - Virtual IoT device
- [x] Build and test lab - Jupyter notebook for visualizing growing degree day data
- [x] Pre and post quiz questions
- [x] Sketchnote
