### ISSUE TITLE
Lesson 6 – Detecting soil moisture

### ISSUE THREAD

**Issue by jimbobbennett** [microsoft/IoT-For-Beginners#13]
# Lesson

## Concepts taught

* IoT can implement feedback loops to control actuators based off sensor data, such as watering dry soil.
* The underlying implementation of how sensors and actuators communicate (I2C, SPI, UART)
* Sensors sometimes need to be calibrated

## Learning objectives

* Learn how to measure soil moisture.
* Learn about I2C, SPI, UART (this is a light lesson as the concepts are not new, so is a good time to add additional knowledge)

## Hardware required

* Wio/Pi
* Grove capacitive soil moisture sensor

## Software/services

* VS Code
* PlatformIO (Wio)

## Code

* On-device code to read soil moisture

# Tasks

- [x] Write lesson
- [x] Import I2C/SPI/UART lesson material from [communication-on-devices.md](https://github.com/jimbobbennett/IoT-Dev-For-Beginners/blob/main/content-for-future-lessons/communication-on-devices.md)
- [x] Build and test lab - Wio Terminal
- [x] Build and test lab - Raspberry Pi
- [x] Build and test lab - Virtual IoT device
- [x] [Add capacitive soil moisture sensor to CounterFit](https://github.com/CounterFit-IoT/CounterFit/issues/4)
- [x] Pre and post quiz questions
- [x] Sketchnote
