### ISSUE TITLE
Lesson 7 - Automated plant watering

### ISSUE THREAD

**Issue by jimbobbennett** [microsoft/IoT-For-Beginners#14]
# Lesson

## Concepts taught

* Sensors may not provide an immediate reading.
* Actuators can control additional hardware
* IoT feedback loops can be controlled from the cloud to allow decisions to be made using more data than a single sensor, or to allow actuators to be controlled when not connected to the sensor.

## Learning objectives

* Learn how to send soil moisture data and control the relay over MQTT.
* Learn about feedback delays such as waiting for water to soak into the soil before checking the moisture sensor.
* Learn how to create server-side logic to listen for telemetry on the MQTT broker and send commands back.

## Hardware required

* Wio/Pi
* Grove capacitive soil moisture sensor
* Grove relay
* Pump (optional)

## Software/services

* VS Code
* PlatformIO (Wio)

## Code

* On-device code to read soil moisture and send over MQTT and listen to MQTT to control the relay.
* The relay is left on for a fixed time, then wait for a fixed time before taking the next measurement.
* Local server code to control the relay on time and wait for soil moisture changes.

# Tasks

- [x] Write lesson
- [x] Build and test lab - Wio Terminal
- [x] Build and test lab - Raspberry Pi
- [x] Build and test lab - Virtual IoT device
- [x] Build and test lab - 'server' code
- [x] Pre and post quiz questions
- [x] Sketchnote
