### ISSUE TITLE
Lesson 8 – Moving your plant to the cloud

### ISSUE THREAD

**Issue by jimbobbennett** [microsoft/IoT-For-Beginners#15]
# Lesson

## Concepts taught

* The cloud provides hosted IoT gateways you can use with your IoT devices to save hosting your own.

## Learning objectives

* Learn the principles of cloud hosting.
* Learn about Azure IoT Hub.
* Learn how to migrate soil control to IoT Hub.

* Wio/Pi
* Grove capacitive soil moisture sensor
* Grove relay
* Pump (optional)

## Software/services

* VS Code
* PlatformIO (Wio)
* IoT Hub (free tier)

## Code

* On-device code to read soil moisture and send to IoT Hub and listen to IoT Hub to control the relay.

# Tasks

- [x] Write lesson
- [x] Build and test lab - IoT Hub deployment via the CLI
- [x] Build and test lab - Wio Terminal
- [x] Build and test lab - Raspberry Pi
- [x] Build and test lab - Virtual IoT device
- [x] Pre and post quiz questions
- [ ] Sketchnote
