### ISSUE TITLE
Lesson 10 – Keep your plant secure

### ISSUE THREAD

**Issue by jimbobbennett** [microsoft/IoT-For-Beginners#16]
# Lesson

## Concepts taught

* IoT devices need to connect securely to avoid bad actors.
* You can secure an IoT device with a symmetric key, or a certificate.
* You should clean up cloud resources once you have finished a project to save money or free resources.

## Learning objectives

* Learn the principles IoT security.
* Learn about symmetric keys.
* Learn about x.509 certificates.
* Learn how to generate and use a test certificate.
* Learn about cleaning up cloud resources.

## Hardware required

* Wio/Pi
* Grove capacitive soil moisture sensor
* Grove relay
* Pump (optional)

## Software/services

* VS Code
* PlatformIO (Wio)
* IoT Hub (free tier)

## Code

* On-device code to read soil moisture and send to IoT Hub and listen to IoT Hub to control the relay, secured using x.509.

# Tasks

- [x] Write lesson
- [x] Build and test lab - IoT Hub certificate setup
- [x] Build and test lab - Wio Terminal
- [x] Build and test lab - Raspberry Pi
- [x] Build and test lab - Virtual IoT device
- [x] Pre and post quiz questions
- [ ] Sketchnote
