### ISSUE TITLE
Lesson 9 – Transplant your application logic to the cloud

### ISSUE THREAD

**Issue by jimbobbennett** [microsoft/IoT-For-Beginners#17]
# Lesson

## Concepts taught

* The logic code that controls the relay can live in event-driven code in the cloud.
* Using serverless you can respond to IoT telemetry and control IoT devices with custom logic that is only called when telemetry is received.

## Learning objectives

* Learn the principles of serverless.
* Learn about Azure Functions.
* Learn how to listen for telemetry in an Azure Function.
* Learn how to control IoT devices from an Azure Function.
* Learn how to run Azure Functions locally, then deploy to the cloud.

## Hardware required

* Wio/Pi
* Grove capacitive soil moisture sensor
* Grove relay
* Pump (optional)

## Software/services

* VS Code
* PlatformIO (Wio)
* IoT Hub (free tier)
* Azure Functions CLI
* Azure Functions (consumption plan, within the free quantity)

## Code

* On-device code to read soil moisture and send to IoT Hub and listen to IoT Hub to control the relay.
* Azure Functions event hub trigger connected to IoT Hub to control the relay on a timer and wait for soil moisture changes.

# Tasks

- [x] Write lesson
- [x] Build and test lab - Install the Azure Functions CLI
- [x] Build and test lab - Local Azure Functions
- [x] Build and test lab - Deploy Azure Functions to the cloud
- [x] Pre and post quiz questions
- [ ] Sketchnote
