### ISSUE TITLE
Lesson 12 - storing location data

### ISSUE THREAD

**Issue by jimbobbennett** [microsoft/IoT-For-Beginners#18]
# Lesson

## Concepts taught

* IoT data is not stored by IoT services, it needs to be manually stored somewhere
* IoT data is unstructured, so is better suited for NoSQL database
* Azure storage includes blob storage for IoT data

## Learning objectives

* Learn about the differences between SQL and NoSQL storage
* Learn about the differences between Table and Blob storage
* Learn how to save IoT data into an Azure Storage Account blob storage

## Hardware required

* Wio/Pi
* Grove GPS sensor

## Software/services

* VS Code
* PlatformIO (Wio)
* IoT Hub (free tier)
* Azure Functions
* Azure Storage Account

## Code

* On-device code to read and decode GPS data
* Azure Functions to store GPS data

# Tasks

- [x] Write lesson
- [x] Build and test lab - IoT Hub, Azure Functions, and storage account deployment
- [x] Build and test lab - Wio Terminal
- [x] Build and test lab - Raspberry Pi
- [x] Build and test lab - Virtual IoT device
- [ ] Pre and post quiz questions
- [ ] Sketchnote
