### ISSUE TITLE
Lesson 11 – Location tracking

### ISSUE THREAD

**Issue by jimbobbennett** [microsoft/IoT-For-Beginners#19]
# Lesson

## Concepts taught

* IoT devices can track location using GPS coordinates.
* GPS is based on positions on the globe and can define any point.
* GPS positioning is based off time signals from satellites and is not millimeter accurate.
* GPS data comes in [NMEA](https://en.wikipedia.org/wiki/NMEA_0183) format.

## Learning objectives

* Learn about geo-spatial coordinates.
* Learn how to capture and decode NMEA GPS data from a GPS sensor.

## Hardware required

* Wio/Pi
* Grove GPS sensor

## Software/services

* VS Code
* PlatformIO (Wio)
* IoT Hub (free tier)

## Code

* On-device code to read and decode GPS data
* On-device decoding of NMEA sentences using a third party library

# Tasks

- [x] Write lesson
- [x] Build and test lab - Wio Terminal with library for NMEA decode
- [x] Build and test lab - Raspberry Pi with library for NMEA decode
- [x] Build and test lab - Virtual IoT device with library for NMEA decode
- [x] [ Add GPS sensor to CounterFit](https://github.com/CounterFit-IoT/CounterFit/issues/6)
- [ ] Pre and post quiz questions
- [ ] Sketchnote
