### ISSUE TITLE
Lesson 13 – Visualizing location data

### ISSUE THREAD

**Issue by jimbobbennett** [microsoft/IoT-For-Beginners#20]
# Lesson

## Concepts taught

* IoT data can be visualized on dashboards in different forms depending on the data.
* Location data can be visualized on a map that uses a Mercator projection to ‘flatten’ the globe.

## Learning objectives

* Learn about the Mercator projection.
* Learn how to use the Azure Maps web SDK to show a map.
* Learn about the GeoJSON format
* Learn how to plot IoT data on the map using GeoJSON, and how GeoJSON uses lon,lat for points, not lat,lon

## Hardware required

* Wio/Pi
* Grove GPS sensor

## Software/services

* VS Code
* PlatformIO (Wio)
* IoT Hub (free tier), Azure Functions, Azure Storage
* Azure Maps (S1 tier, usage in the free quantity)

## Code

* On-device code to read and decode GPS data, and send to IoT Hub, then a function app, then storage (from previous lesson)
* Local web app to show the Azure Maps web SDK and plot the GPS location

# Tasks

- [x] Write lesson
- [x] Build and test lab - set up Azure Maps with the CLI
- [x] Build and test lab - Web app
- [ ] Pre and post quiz questions
- [ ] Sketchnote
