### ISSUE TITLE
Lesson 14 – Geofencing

### ISSUE THREAD

**Issue by jimbobbennett** [microsoft/IoT-For-Beginners#21]
# Lesson

## Concepts taught

* Geofences are defined geospatial areas.
* A GPS location can be tested to see if it is inside or outside the Geofence.
* GPS is not accurate, and this comes into the testing of the geofence.

## Learning objectives

* Learn about geofences.
* Learn how to define a Geofence using Azure Maps.
* Learn how to test a point against a Geofence using Azure Maps.
* Learn about consumer groups to run multiple Azure Functions against the same IoT Hub

## Hardware required

* Wio/Pi
* Grove GPS sensor

## Software/services

* VS Code
* PlatformIO (Wio)
* IoT Hub (free tier)
* Azure Maps (S1 tier, usage in the free quantity)

## Code

* On-device code to read and decode GPS data, and send to IoT Hub.
* Local script to define a geofence.
* Azure Functions app to detect if a vehicle is within a geofence and alert if not.

# Tasks

- [x] Write lesson
- [x] Build and test lab - define geofence
- [x] Build and test lab - test geofence
- [ ] Pre and post quiz questions
- [ ] Sketchnote
