### ISSUE TITLE
Lesson 15 – Training a fruit quality detector

### ISSUE THREAD

**Issue by jimbobbennett** [microsoft/IoT-For-Beginners#22]
# Lesson

## Concepts taught

* AI can detect images and can be trained to classify fruit based on good or bad.
* Transfer learning allows image classifiers to be trained with only a small number of images.

## Learning objectives

* Learn about image classifiers.
* Learn how to train an image classifier to compare good and bad fruit, then test it.

## Hardware required

* None

## Software/services

* Custom Vision
* Cognitive services resource (free tier)

## Code

* None

# Tasks

- [x] Write lesson
- [x] Gather sample image data
- [x] Build and test lab - create cognitive services resource with the CLI
- [x] Build and test lab - train an image classifier
- [ ] Pre and post quiz questions
- [ ] Sketchnote
