### ISSUE TITLE
Lesson 16 – Checking fruit quality from an IoT device

### ISSUE THREAD

**Issue by jimbobbennett** [microsoft/IoT-For-Beginners#23]
# Lesson

## Concepts taught

* IoT devices can use cameras and send the images to AI services for image classification.

## Learning objectives

* Learn how to capture images with a camera.
* Learn how to use the custom vision APIs to check fruit.
* Learn how to improve the model.

## Hardware required

* Wio/Pi
* Grove camera sensor or Pi camera
* Fruit

## Software/services

* VS Code
* PlatformIO (Wio)
* Custom Vision
* Cognitive services resource (free tier)

## Code

* On-device code to capture an image from the camera and send it to the custom vision API.

# Tasks

- [x] Write lesson
- [x] Build and test lab - Wio Terminal
- [x] Build and test lab - Raspberry Pi
- [x] Build and test lab - Virtual IoT device
- [x] [Add PyCamera support to CounterFit](https://github.com/CounterFit-IoT/CounterFit/issues/2)
- [ ] Pre and post quiz questions
- [ ] Sketchnote
