### ISSUE TITLE
Lesson 17 – Running AI models on the edge

### ISSUE THREAD

**Issue by jimbobbennett** [microsoft/IoT-For-Beginners#24]
# Lesson

## Concepts taught

* AI models can be run on the edge – so running on IoT devices closer to the sensors.
* This is faster, private and can be cheaper.

## Learning objectives

* Learn about the upsides to running IoT models on the edge such as privacy and speed.
* Learn the downside of running IoT models on the edge such as resiliency and having to manually capture data to retrain the model.
* Learn how to run the custom vision model on the edge with IoT Edge (either on a Pi, or on your device)

## Hardware required

* Wio/Pi
* Grove camera sensor or Pi camera
* Fruit

## Software/services

* VS Code
* PlatformIO (Wio)
* IoT Hub (free tier)
* Custom Vision
* Cognitive services resource (free tier)

## Code

* On-device code to capture an image from the camera and send it to the custom vision API running on the edge.

# Tasks

- [x] Write lesson
- [x] Build and test lab - IoT Hub setup with the CLI
- [x] Build and test lab - IoT Edge setup with the CLI
- [x] Build and test lab - Local IoT Edge deployment
- [x] Build and test lab - Raspberry Pi IoT Edge deployment
- [x] Build and test lab - Wio Terminal
- [x] Build and test lab - Wio Terminal
- [x] Build and test lab - Raspberry Pi
- [x] Build and test lab - Virtual IoT device
- [x] Pre and post quiz questions
- [ ] Sketchnote
