### ISSUE TITLE
Lesson 18 – Triggering the AI model call from a sensor

### ISSUE THREAD

**Issue by jimbobbennett** [microsoft/IoT-For-Beginners#25]
# Lesson

## Concepts taught

* Many components would work together for checking quality – a sensor would detect that an item needs to be checked, an image would be taken, and feedback would be given via an actuator.
* Serverless code can manage these devices working together.

## Learning objectives

* Learn about end-to-end solutions with multiple components.
* Learn how to build an end-to-end fruit quality monitor by connecting multiple different devices via the cloud

## Hardware required

* Wio/Pi
* Grove camera sensor or Pi camera
* Grove proximity sensor
* Red and green Grove LEDs
* Fruit

## Software/services

* VS Code
* PlatformIO (Wio)
* IoT Hub (free tier)

## Code

* On-device code to read from the proximity sensor and send a message to IoT hub.
* Local server-side code to listen for this message and send a command to capture a photo and run it through the AI model.
* On-device code to listen for this request, take a photo, send it to the custom vision API on the edge and return the results.
* Local Azure Functions code to send a request to report the quality status.
* On-device code to listen to the status and display it using LEDs

* 

# Tasks

- [x] Write lesson
- [x] Build and test lab - Wio Terminal
- [x] Build and test lab - Raspberry Pi
- [x] Build and test lab - Virtual IoT device
- [x] [Add Grove Proximity sensor](https://github.com/CounterFit-IoT/CounterFit/issues/7)
- [ ] Pre and post quiz questions
- [ ] Sketchnote
