### ISSUE TITLE
Lesson 19 – Training a stock detector

### ISSUE THREAD

**Issue by jimbobbennett** [microsoft/IoT-For-Beginners#26]
# Lesson

## Concepts taught

* AI can be trained to detect objects in an image, not just classify images.
* It can be used to count images, giving an indication when an item needs to be re-stocked on a store shelf.

## Learning objectives

* Learn about object detection.
* Learn how to train an object detector to count produce.

## Hardware required

* Identical objects (such as cereal boxes)

## Software/services

* Custom Vision
* Cognitive services resource (free tier)

## Code

* None

# Tasks

- [x] Write lesson
- [x] Build and test lab - create cognitive servies resource
- [x] Build and test lab - create custom vision object detector
- [ ] Pre and post quiz questions
- [ ] Sketchnote
