### ISSUE TITLE
Lesson 20 – Checking stock from an IoT device

### ISSUE THREAD

**Issue by jimbobbennett** [microsoft/IoT-For-Beginners#27]
# Lesson

## Concepts taught

* IoT devices can use cameras and send the images to AI services for object detection. 

## Learning objectives

* Learn how to use the custom vision APIs to count objects.
* Learn how to improve the model.

## Hardware required

* Wio/Pi
* Grove camera sensor or Pi camera
* Identical objects (such as cereal boxes)

## Software/services

* VS Code
* PlatformIO (Wio)
* Custom Vision
* Cognitive services resource (free tier), IoT Hub (free tier)

## Code

* On-device code to capture an image from the camera and send it to the custom vision API

# Tasks

- [x] Write lesson
- [x] Build and test lab - Wio Terminal
- [x] Build and test lab - Raspberry Pi
- [x] Build and test lab - Virtual IoT device
- [ ] Pre and post quiz questions
- [ ] Sketchnote
