### ISSUE TITLE
Lesson 21 – Speech recognition

### ISSUE THREAD

**Issue by jimbobbennett** [microsoft/IoT-For-Beginners#28]
# Lesson

## Concepts taught

* IoT devices can capture audio and use AI services in the cloud for speech detection.

## Learning objectives

* Learn about pre-built AI services.
* Learn how to capture audio.
* Learn how to use AI services to convert speech to text.

## Hardware required

* Wio/Pi
* USB Microphone (Pi)
* Grove button (Pi)

## Software/services

* VS Code
* PlatformIO (Wio)
* Cognitive services resource (free tier)

## Code

* On-device code to capture audio when the button is pressed and send it to the cloud to convert to text.

# Tasks

- [x] Write lesson
- [x] Build and test lab - Set up cognitive services speech with the CLI
- [x] Build and test lab - Wio Terminal
- [x] Build and test lab - Raspberry Pi
- [x] Build and test lab - Virtual IoT device
- [x] Pre and post quiz questions
- [x] Sketchnote
