### ISSUE TITLE
Lesson 22 – Language understanding

### ISSUE THREAD

**Issue by jimbobbennett** [microsoft/IoT-For-Beginners#29]
# Lesson

## Concepts taught

* AI services can be trained to understand language.
* They can extract entities and intents, such as how long to set a timer for.

## Learning objectives

* Learn how to configure language understanding.
* Learn how to call a language understanding model from an IoT device.
 
## Hardware required

* Wio/Pi
* USB Microphone (Pi)
* Grove button (Pi)

## Software/services

* VS Code
* PlatformIO (Wio)
* Cognitive services resource (free tier)

## Code

* On-device code to capture audio when the button is pressed and send it to the cloud to convert to text.
* The text is then processed using the language understanding model.

# Tasks

- [x] Write lesson
- [x] Build and test lab - set up LUIS
- [x] Build and test lab - Functions app
- [x] Pre and post quiz questions
- [x] Sketchnote
