### ISSUE TITLE
Lesson 23 – Giving spoken feedback

### ISSUE THREAD

**Issue by jimbobbennett** [microsoft/IoT-For-Beginners#30]
# Lesson

## Concepts taught

* AI models can convert text to spoken words, using a variety of voice models.
* This speech can be played on an IoT device.

## Learning objectives

* Learn about text to speech.
* Learn about different voice models.
* Learn how to convert text to speech using an AI service and play the speech on an IoT device.

## Hardware required

* Wio/Pi
* USB Microphone (Pi)
* Grove button (Pi)
* Grove speaker (Wio)
* USB speaker (Pi)

## Software/services

* VS Code
* PlatformIO (Wio)
* Cognitive services resource (free tier)

## Code

* On-device code to capture audio when the button is pressed and send it to the cloud to convert to text.
* The text is then processed using the language understanding model.
* On-device code to speak the response to the spoken command, as well as speak when the timer is up.

# Tasks

- [x] Write lesson
- [ ] Build and test lab - Wio Terminal
- [x] Build and test lab - Raspberry Pi
- [x] Build and test lab - Virtual IoT device
- [x] Pre and post quiz questions
- [x] Sketchnote
