### ISSUE TITLE
Lesson 24 – Multiple language support

### ISSUE THREAD

**Issue by jimbobbennett** [microsoft/IoT-For-Beginners#31]
# Lesson

## Concepts taught

* AI models can translate between different languages.
* Spoken words can be translated into one language, processed for language understanding, and the result translated back to the original language.

## Learning objectives

* Learn about AI translations.
* Learn how to translate the incoming speech, detecting the language.
* Learn how to translate the outgoing speech to the original detected language.

## Hardware required

* Wio/Pi
* USB Microphone (Pi)
* Grove button (Pi)
* Grove speaker (Wio)
* USB speaker (Pi)

## Software/services

* VS Code
* PlatformIO (Wio)
* Cognitive services resource (free tier)

## Code

* On-device code to capture audio when the button is pressed and send it to the cloud to get the language spoken and convert to text in a common language.
* The text is then processed using the language understanding model.
* Responses are given in the initial language

# Tasks

- [x] Write lesson
- [ ] Build and test lab - Wio Terminal
- [x] Build and test lab - Raspberry Pi
- [x] Build and test lab - Virtual IoT device
- [x] Pre and post quiz questions
- [x] Sketchnote
